"""Tunable limits and well-known names.

Nothing outside this module hardcodes a size, threshold, filename, or env var.
"""

from __future__ import annotations

from .model import DocKind, LinkType, ReadWhen

FRONTMATTER_DELIMITER = "---"
DOC_FILE_SUFFIX = ".md"

SPINE_HOME_ENV_VAR = "SPINE_HOME"
SPINE_SESSION_ID_ENV_VAR = "SPINE_SESSION_ID"
SPINE_PROJECT_ENV_VAR = "SPINE_PROJECT"
SPINE_DISABLED_ENV_VAR = "SPINE_DISABLED"

DEFAULT_SPINE_DIR_NAME = "spine"
REGISTRY_FILE_NAME = "registry.toml"
GRAPH_DB_FILE_NAME = "graph.sqlite3"
SESSIONS_DIR_NAME = "sessions"
PICKS_DB_FILE_NAME = "picks.sqlite3"

PROJECT_SLUG_SEPARATOR = "-"
DOC_ID_SEPARATOR = ":"

MAX_LINES_PER_READ_WHEN: dict[ReadWhen, int] = {
    ReadWhen.EVERY_TIME: 700,
    ReadWhen.IN_AREA: 1200,
    ReadWhen.RARELY: 4000,
    ReadWhen.LOOKED_UP: 4000,
    ReadWhen.LOG: 4000,
}

INJECTION_LINE_BUDGET = 2500
EVERY_TIME_RESERVED_LINES = 700

MIN_CONFIDENCE_FOR_SILENT_PICK = 0.6
MIN_CONFIDENCE_FOR_AUTO_ATTACH = 0.5
EXACT_MATCH_CONFIDENCE = 1.0
NO_MATCH_CONFIDENCE = 0.0

MODEL_INFERRED_LINK_CONFIDENCE = 0.7
TEXTUAL_LINK_CONFIDENCE = 1.0

REGISTRY_PROJECTS_TABLE = "projects"
REGISTRY_KEY_NAME = "name"
REGISTRY_KEY_DOCS_DIR = "docs_dir"
REGISTRY_KEY_REPOS = "repos"
REGISTRY_KEY_PATH_GLOBS = "path_globs"
REGISTRY_KEY_BRANCH_PREFIXES = "branch_prefixes"
REGISTRY_KEY_LINEAR_PROJECT = "linear_project"
REGISTRY_BARE_KEY_EXTRA_CHARS = "-_"

REPO_MATCH_CONFIDENCE = 0.6
BRANCH_PREFIX_MATCH_CONFIDENCE = 0.5
PATH_GLOB_MATCH_CONFIDENCE = 0.4
PROMPT_MENTION_CONFIDENCE = 0.3
DOC_TEXT_ENCODING = "utf-8"

FRONTMATTER_KEY_SEPARATOR = ":"
FRONTMATTER_COMMENT_PREFIX = "#"
FRONTMATTER_NULL_LITERAL = "null"
FRONTMATTER_TRUE_LITERAL = "true"
FRONTMATTER_FALSE_LITERAL = "false"
FRONTMATTER_LIST_OPEN = "["
FRONTMATTER_LIST_CLOSE = "]"
FRONTMATTER_LIST_ITEM_SEPARATOR = ","
FRONTMATTER_QUOTE_CHARACTERS = ('"', "'")

DOC_KIND_KEY = "kind"
DOC_READ_WHEN_KEY = "read_when"
DOC_TITLE_KEY = "title"
DOC_AREA_KEY = "area"
DOC_LIFECYCLE_KEY = "lifecycle"
DOC_GENERATED_KEYS = ("generated", "is_generated")

MARKDOWN_H1_PREFIX = "# "
MARKDOWN_FENCE_PREFIX = "```"
FILENAME_WORD_SEPARATOR = "-"
DOC_KIND_WORD_SEPARATOR = "_"

DOC_KIND_BY_FILENAME_PREFIX: dict[str, DocKind] = {
    "brief": DocKind.BRIEF,
    "rules": DocKind.PROJECT_RULES,
    "classification": DocKind.CLASSIFICATION,
    "milestone": DocKind.MILESTONE,
    "design": DocKind.AREA_DESIGN,
    "rollout": DocKind.ROLLOUT,
    "test-coverage": DocKind.TEST_COVERAGE,
    "decisions": DocKind.DECISION_LOG,
    "decision-log": DocKind.DECISION_LOG,
    "open-questions": DocKind.OPEN_QUESTIONS,
}
FALLBACK_DOC_KIND = DocKind.GENERATED

DOCS_COMMAND_NAME = "docs"
DOCS_LIST_ACTION = "list"
DOCS_CHECK_ACTION = "check"
DOCS_ACTION_DEST = "docs_action"
DOCS_DIR_OPTION = "--dir"
DOCS_DIR_DEST = "docs_dir"

DOCS_MISSING_DIR_MESSAGE = "no corpus directory at {docs_dir}"
DOCS_LIST_ROW_FORMAT = "{doc_id}\t{kind}\t{read_when}\t{line_count}\t{title}"
DOCS_BREACH_ROW_FORMAT = "{doc_id}\t{read_when}\t{line_count}/{cap_lines} lines\t+{excess_lines}"

EXIT_CAP_BREACH = 1
CITATION_LINK_TYPES: frozenset[LinkType] = frozenset(
    {
        LinkType.BLOCKS,
        LinkType.CLASSIFIES,
        LinkType.CONSTRAINS,
        LinkType.DEPENDS_ON,
        LinkType.DERIVED_FROM,
        LinkType.IMPLEMENTS,
        LinkType.MENTIONS,
        LinkType.RAMPS,
        LinkType.VERIFIES,
    }
)
UNKNOWN_SESSION_ID = "unknown"

AREA_MATCH_WEIGHT = 3.0
TITLE_TERM_OVERLAP_WEIGHT = 2.0
GRAPH_PROXIMITY_WEIGHT = 1.0
MIN_RANKING_TERM_LENGTH = 3
MARKDOWN_HEADING_PREFIX = "#"
RANKING_TERM_PATTERN = r"[^\W_]+"
RANKING_SCORE_PRECISION = 9

BULK_INJECTION_GROUP_ORDER: tuple[ReadWhen, ...] = (ReadWhen.EVERY_TIME, ReadWhen.IN_AREA)
ON_REQUEST_GROUP_ORDER: tuple[ReadWhen, ...] = (ReadWhen.RARELY,)

PICK_REASON_ALL_FIT = "all_candidates_fit"
PICK_REASON_NO_CANDIDATES = "no_candidates"
PICK_REASON_BUDGET_EXHAUSTED = "budget_exhausted"
PICK_REASON_EVERY_TIME_OVER_RESERVE = "every_time_over_reserve"

PICKS_TABLE_NAME = "picks"
DOC_ID_LIST_SEPARATOR = ","
PICKS_DB_BUSY_TIMEOUT_SECONDS = 5.0

GRAPH_STORE_MODULE_NAME = "index"
GRAPH_STORE_FACTORY_NAME = "open_graph_store"
PROJECT_REGISTRY_MODULE_NAME = "registry"
PROJECT_REGISTRY_FACTORY_NAME = "load_registry"

ENTRY_ANCHOR_SEPARATOR = "#"
ENTRY_HEADING_PREFIX = "## "
ENTRY_SLUG_SEPARATOR = "-"
ENTRY_SLUG_ALLOWED_EXTRA = "-"
MIN_ENTRY_TITLE_TERM_LENGTH = 4
MIN_ENTRY_MATCH_TERMS = 1

SEGMENTED_DOC_KINDS: frozenset[DocKind] = frozenset(
    {DocKind.DECISION_LOG, DocKind.OPEN_QUESTIONS}
)

CLASSIFIER_MODEL_ID = "claude-opus-5"
CLASSIFIER_EFFORT = "low"
CLASSIFIER_MAX_TOKENS = 8000
CLASSIFIER_BATCH_SIZE = 12
CLASSIFIER_EXCERPT_CHARS = 1200
CLASSIFIER_PROMPT_VERSION = "2"
CLASSIFIER_CACHE_FILE_NAME = "classifications.sqlite3"
CLASSIFIER_MIN_CONFIDENCE = 0.5
ANTHROPIC_PACKAGE_NAME = "anthropic"

DASHBOARD_HOST = "127.0.0.1"
DASHBOARD_PORT = 8791
DASHBOARD_PICK_BUDGET = 2500
HEALTH_DUPLICATE_TITLE_SIMILARITY = 0.82
HEALTH_MAX_EVERY_TIME_DOCS = 3

DASHBOARD_PROBE_TIMEOUT_SECONDS = 2.0

ATTACH_CONFIDENCE_MARGIN = 0.05
SESSION_CONTEXT_TOTAL_BUDGET = 700

MAX_AUTO_ATTACH_PROJECTS = 2

FACTS_DB_FILE_NAME = "facts.sqlite3"
FACTS_COMMIT_LIMIT = 200
FACTS_PR_LIMIT = 50
FACTS_LOOKBACK_DAYS = 30
GIT_LOG_FORMAT = "%H%x1f%an%x1f%aI%x1f%s"
GIT_FIELD_SEPARATOR = "\x1f"
GITHUB_CLI_PATH = "/opt/homebrew/bin/gh"
FACTS_MIN_TITLE_TERM_LENGTH = 4
SUBPROCESS_TIMEOUT_SECONDS = 20

SESSIONS_DB_FILE_NAME = "live_sessions.sqlite3"
SESSION_LEASE_SECONDS = 900
SESSION_STALE_SECONDS = 1800
STEERING_INBOX_DIR_NAME = "steering"
BROADCAST_FILE_NAME = "broadcasts.jsonl"
MAX_BROADCAST_REPLAY = 50

GUARD_UNDECLARED_MESSAGE = "this session has not said what it is doing"
GUARD_OUTSIDE_SCOPE_MESSAGE = "editing outside what this session declared"
CRITIQUE_MAX_ROUNDS = 3
CRITIQUE_MODEL_ID = "claude-opus-5"
CRITIQUE_EFFORT = "medium"
CRITIQUE_MAX_TOKENS = 8000

PROPOSALS_DB_FILE_NAME = "proposals.sqlite3"
PROPOSAL_APPEND_HEADING = "## Shipped since this document was written"
PROPOSAL_MAX_PER_PROJECT = 25

DRIFT_MAX_REPORTED_DOCS = 8

STYLE_MAX_SENTENCE_WORDS = 34
CRITIQUE_MAX_GROWTH_RATIO = 1.5

PLAN_SETTLED_STATUSES = frozenset({"done"})
PLAN_STALLED_STATUSES = frozenset({"blocked"})
PLAN_STATUS_COLUMN_NAMES = frozenset({"status", "state"})
PLAN_EVIDENCE_COLUMN_NAMES = frozenset({"evidence", "remaining", "note", "notes"})
PLAN_OPEN_QUESTION_HEADINGS = ("open question", "open item", "unresolved")
PLAN_MAX_ITEMS_PER_PROJECT = 400
PLAN_MAX_OPEN_QUESTIONS = 20
PLAN_CONTEXT_MAX_ITEMS = 6
PLAN_BEARING_KINDS = frozenset({"milestone", "rollout", "open_questions"})

COLLISION_MAX_REPORTED = 10
DECISION_REVIEW_MAX_SHOWN = 8
DECISIONS_DB_FILE_NAME = "decisions.sqlite3"
PLAN_DONE_WEIGHT = 10
HEALTH_DUPLICATE_BODY_OVERLAP = 0.5
